### ISSUE TITLE
Featured are not called if not parameter of the callback

### ISSUE THREAD

**Issue by jsoulet** [iadvize/javascript-ioc-library#4]
The lib should proactively inform the developper if one of the dependancy is not par of the callback parameters and won't be called

**Comment by FGRibreau** [comment]
**Wanted**:

`addCoreFeature` and `addFeature` should throw if there is a mismatch between the dependency declaration (e.g. `['dep1', 'dep2']`) AND the function arguments (e.g. `function feature(dep1)`, `dep2` is missing).
